name: Docker Image CI - zeppelin:0.8.2-oj11-base

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai
      DOCKER_USER: dockergum
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      IMAGE_NAME: dockergum/zeppelin:0.8.2-oj11-base
    
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker push $IMAGE_NAME